name: Check Timeout

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: write

jobs:
  check-timeout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Check Timeout
        run: python check_timeout.py
      - name: Commit Results
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add timeouts.md
          git commit -am "chore: auto update timeout results" || echo "Nothing to update."
          git push