name: Report Timeout

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 14 * * *'

permissions:
  contents: write

jobs:
  check-timeout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Report Timeout
        run: python report.py
      - name: Commit Results
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add timeout.csv
          git add timeout.png
          git commit -am "chore: auto update report" || echo "Nothing to update."
          git push